namespace D2
{
    partial class Statistics
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.listBoxStatistics = new System.Windows.Forms.ListBox();
            this.comboBoxStats = new System.Windows.Forms.ComboBox();
            this.buttonBack = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label1.Location = new System.Drawing.Point(327, 9);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(453, 128);
            this.label1.TabIndex = 0;
            this.label1.Text = "Statistics";
            // 
            // listBoxStatistics
            // 
            this.listBoxStatistics.FormattingEnabled = true;
            this.listBoxStatistics.ItemHeight = 25;
            this.listBoxStatistics.Location = new System.Drawing.Point(106, 228);
            this.listBoxStatistics.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.listBoxStatistics.Name = "listBoxStatistics";
            this.listBoxStatistics.Size = new System.Drawing.Size(938, 479);
            this.listBoxStatistics.TabIndex = 12;
            // 
            // comboBoxStats
            // 
            this.comboBoxStats.FormattingEnabled = true;
            this.comboBoxStats.Items.AddRange(new object[] {
            "Number of unique customers who rented equipment in each branch",
            "Average rental duration per equipment type",
            "Most popular equipment type rented in each branch",
            "The total number of rentals per month",
            "Total income generated by each equipment type"});
            this.comboBoxStats.Location = new System.Drawing.Point(349, 180);
            this.comboBoxStats.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.comboBoxStats.Name = "comboBoxStats";
            this.comboBoxStats.Size = new System.Drawing.Size(441, 33);
            this.comboBoxStats.TabIndex = 13;
            this.comboBoxStats.SelectedIndexChanged += new System.EventHandler(this.comboBoxStats_SelectedIndexChanged);
            // 
            // buttonBack
            // 
            this.buttonBack.Location = new System.Drawing.Point(888, 174);
            this.buttonBack.Name = "buttonBack";
            this.buttonBack.Size = new System.Drawing.Size(128, 42);
            this.buttonBack.TabIndex = 14;
            this.buttonBack.Text = "Back";
            this.buttonBack.UseVisualStyleBackColor = true;
            this.buttonBack.Click += new System.EventHandler(this.buttonBack_Click);
            // 
            // Statistics
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 25F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1143, 750);
            this.Controls.Add(this.buttonBack);
            this.Controls.Add(this.comboBoxStats);
            this.Controls.Add(this.listBoxStatistics);
            this.Controls.Add(this.label1);
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "Statistics";
            this.Text = "Statistics";
            this.Load += new System.EventHandler(this.Statistics_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Label label1;
        private ListBox listBoxStatistics;
        private ComboBox comboBoxStats;
        private Button buttonBack;
    }
}